attention_head_size: 1
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 32
learning_rate: 0.03
log_gradient_flow: false
log_interval: 10
log_val_interval: null
lstm_layers: 1
max_encoder_length: 30
monotone_constaints: {}
optimizer: Ranger
optimizer_params: null
output_size:
- 1
- 1
output_transformer: !!python/object:pytorch_forecasting.data.encoders.MultiNormalizer
  fitted_: true
  normalizers:
  - !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
    center: true
    center_: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYCQAAADI3MDM5OTY4MHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADI3MDM5OTY4
        MHEBYS4BAAAAAAAAACUWUUY=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    max_length: null
    method: standard
    method_kwargs: &id001 {}
    scale_: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYCQAAADI5NTcwNzI0OHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADI5NTcwNzI0
        OHEBYS4BAAAAAAAAACi5JUI=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    transformation: relu
  - !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
    center: true
    center_: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYCQAAADI5NTcwNjE2MHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADI5NTcwNjE2
        MHEBYS4BAAAAAAAAADhcAkY=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    max_length: null
    method: standard
    method_kwargs: *id001
    scale_: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYCQAAADI0MTgzNDA5NnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADI0MTgzNDA5
        NnEBYS4BAAAAAAAAAA6doEI=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    transformation: relu
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- AGV_speed_X
- AGV_speed_Y
- AGV_speed
- User_speed
- User_velocity_X
- User_velocity_Y
- Wait_time
- start_station_X
- start_station_Y
- end_station_X
- end_station_Y
- AGV_X
- AGV_Y
- rolling_avg
time_varying_reals_encoder:
- AGV_speed_X
- AGV_speed_Y
- AGV_speed
- User_speed
- User_velocity_X
- User_velocity_Y
- Wait_time
- start_station_X
- start_station_Y
- end_station_X
- end_station_Y
- AGV_X
- AGV_Y
- rolling_avg
- User_X
- User_Y
- AGV_distance_X
- AGV_distance_Y
- User_speed_X
- User_speed_Y
- distance_to_closest_station
- distance_to_closest_station_X
- distance_to_closest_station_Y
- distance_from_start_station_X
- distance_from_start_station_Y
- distance_from_end_station_X
- distance_from_end_station_Y
- GazeDirection_X
- GazeDirection_Y
- GazeDirection_Z
- Gazing_station
- closest_station
weight_decay: 0.0
x_categoricals: []
x_reals:
- AGV_speed_X
- AGV_speed_Y
- AGV_speed
- User_speed
- User_velocity_X
- User_velocity_Y
- Wait_time
- start_station_X
- start_station_Y
- end_station_X
- end_station_Y
- AGV_X
- AGV_Y
- rolling_avg
- User_X
- User_Y
- AGV_distance_X
- AGV_distance_Y
- User_speed_X
- User_speed_Y
- distance_to_closest_station
- distance_to_closest_station_X
- distance_to_closest_station_Y
- distance_from_start_station_X
- distance_from_start_station_Y
- distance_from_end_station_X
- distance_from_end_station_Y
- GazeDirection_X
- GazeDirection_Y
- GazeDirection_Z
- Gazing_station
- closest_station
